### Get main data
GET https://quote-feed.zacks.com/index.php?t=AVGO
Accept: text/json
Accept-Language: en-US,en;q=0.9
Origin: https://www.zacks.com
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Referer: https://www.zacks.com/stock/quote/AVGO?q=AVGO
x-requested-with: XMLHttpRequest

>>! response.json

### Get earnings calendar
GET https://www.zacks.com/includes/classes/z2_class_calendarfunctions_data.php?calltype=weeklycal&date=1671429600&
    ie_fix=1671482856401
accept: text/json
accept-language: en-US,en;q=0.9
referer: https://www.zacks.com/earnings/earnings-calendar
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

>>! response.json

### Get earnings calendar selected day data
GET https://www.zacks.com/includes/classes/z2_class_calendarfunctions_data.php?calltype=eventscal&date=1671429600&type=1&search_trigger=0&0.33237379349892704&_=1671481877330
accept: text/json
accept-language: en-US,en;q=0.9
referer: https://www.zacks.com/earnings/earnings-calendar
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
x-requested-with: XMLHttpRequest

>>! response.json

### Get daily price data
GET https://www.zacks.com//data_handler/charts/?ticker=AVGO&wrapper=price_and_eps_surprise&addl_settings=
accept: text/json
accept-language: en-US,en;q=0.9
referer: https://www.zacks.com/stock/quote/AVGO?q=AVGO
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

>>! response.json

### Get EPS consensus chart plus weekly price
GET https://www.zacks.com//data_handler/charts/?ticker=AVGO&wrapper=price_and_consensus&
    addl_settings=time_period=2020,2021,2022,2023,2024
accept: application/json
accept-language: en-US,en;q=0.9
referer: https://www.zacks.com/stock/research/AVGO/earnings-calendar
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

>>! response.json

## <HTML PAGES> ##############################

### Earnings Dates and Announcements (calendar data is set as variable obj_data)
GET https://www.zacks.com/stock/research/AVGO/earnings-calendar
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-language: en-US,en;q=0.9
cache-control: no-cache
pragma: no-cache
referer: https://www.zacks.com/stock/research/AVGO/key-company-metrics
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

>>! response.html

### Analyst Ratings
GET https://www.zacks.com/stock/research/AVGO/price-target-stock-forecast
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-language: en-US,en;q=0.9
cache-control: max-age=0
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

>>! response.html

### Style Scores
GET https://www.zacks.com/stock/research/AVGO/stock-style-scores
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-language: en-US,en;q=0.9
cache-control: max-age=0
referer: https://www.zacks.com/stock/research/AVGO/price-target-stock-forecast
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

>>! response.html

### Detailed Earnings Estimates
GET https://www.zacks.com/stock/quote/AVGO/detailed-earning-estimates
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-language: en-US,en;q=0.9
referer: https://www.zacks.com/stock/research/AVGO/stock-style-scores
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

>>! response.html

### Comparison to industry
GET https://www.zacks.com/stock/research/AVGO/industry-comparison
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-language: en-US,en;q=0.9
referer: https://www.zacks.com/stock/research/AVGO/stock-style-scores
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

>>! response.html

### Price Stock Forecast
GET https://www.zacks.com/stock/research/AVGO/price-target-stock-forecast
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-language: en-US,en;q=0.9
referer: https://www.zacks.com/stock/research/AVGO/stock-style-scores
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

>>! response.html

### Financial overview
GET https://www.zacks.com/stock/quote/AVGO/financial-overview
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-language: en-US,en;q=0.9
referer: https://www.zacks.com/stock/research/AVGO/stock-style-scores
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

>>! response.html










